FROM ubuntu:latest

# Add files
COPY ./* /
WORKDIR /

# Install deps
RUN apt-get update \
    && apt-get install -y python3 python3-pip
RUN python3 -m pip install -r requirements.txt

# Start server
EXPOSE 80
RUN python3 main.py
CMD ["python3", "main.py"]
