# Choose a base image
FROM ubuntu:latest

# Install deps
RUN apt-get update \
    && apt-get install -y default-jdk

# Copy in files
COPY stanford-corenlp /stanford-corenlp
WORKDIR /stanford-corenlp


# Start server
EXPOSE 9000
CMD ["java", "-Xmx4g", "-cp", "/stanford-corenlp/*", "edu.stanford.nlp.pipeline.StanfordCoreNLPServer", "-threads", "1", "-timeout", "60000"]
